name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with coverage
      run: dotnet test Tests/Tests.fsproj --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-results
        path: TestResults/
